### ISSUE TITLE
Constant Errors in Unity 5.5.0f3

### ISSUE THREAD

**Issue by xandershelley** [zios/unity-themes#14]
Upon extracting this into assets/plugins, unity gives this error whenever a new page is opened, the game is run, or a folder is doubled clicked. 
Here is the error:
NullReferenceException: Object reference not set to an instance of an object
UnityEditor.EditorStyles.get_miniLabel () (at C:/buildslave/unity/build/Editor/Mono/GUI/EditorStyles.cs:15)
UnityEditor.LookDevEnvironmentWindow+Styles..ctor () (at C:/buildslave/unity/build/Editor/Mono/LookDevView/LookDevEnvironmentWindow.cs:119)
UnityEditor.LookDevEnvironmentWindow..cctor () (at C:/buildslave/unity/build/Editor/Mono/LookDevView/LookDevEnvironmentWindow.cs:137)
Rethrow as TypeInitializationException: An exception was thrown by the type initializer for UnityEditor.LookDevEnvironmentWindow
System.Reflection.MonoField.SetValue (System.Object obj, System.Object val, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Globalization.CultureInfo culture) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Reflection/MonoField.cs:151)
System.Reflection.FieldInfo.SetValue (System.Object obj, System.Object value) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Reflection/FieldInfo.cs:150)
Zios.ObjectExtension.ClearVariable (System.Object current, System.String name, BindingFlags flags)
Zios.Interface.Theme.RebuildStyles ()
Zios.Interface.Theme.Update ()
Zios.Interface.ThemeWindow.OnGUI ()
System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Reflection/MonoMethod.cs:222)
Rethrow as TargetInvocationException: Exception has been thrown by the target of an invocation.
System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Reflection/MonoMethod.cs:232)
System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Reflection/MethodBase.cs:115)
UnityEditor.HostView.Invoke (System.String methodName, System.Object obj) (at C:/buildslave/unity/build/Editor/Mono/HostView.cs:249)
UnityEditor.HostView.Invoke (System.String methodName) (at C:/buildslave/unity/build/Editor/Mono/HostView.cs:242)
UnityEditor.HostView.OnGUI () (at C:/buildslave/unity/build/Editor/Mono/HostView.cs:76)

As well as several other buttons 
(notably the expand folder button in the file browser) and the "services" page not skinning properly. Best guess some hooks changed recently. Looking forward to using this again, thanks!

**Comment by xandershelley** [comment]
![capture](https://cloud.githubusercontent.com/assets/13305268/21190439/99fe9f4c-c1d6-11e6-9db0-b5331351a0c2.PNG)

**Comment by bradsmithee** [comment]
Thanks for the heads up.  I've not developed since August, but I was aware that Unity 5.5 had brought some issues with the theme system.  I'll try to get to them as soon as I'm back into the swing of things!

**Comment by pointcache** [comment]
yep broken completely in 5.5

**Comment by erherhh4herh** [comment]
can't wait for an update!!!!!!

**Comment by bradsmithee** [comment]
Resolved in [Unity 5.5 Hotfix](https://github.com/zios/unity-themes/releases/tag/r522).

**Comment by PyroclasticMayhem** [comment]
I am still having the issue with release 522 on Unity 5.5.0.

**Comment by bradsmithee** [comment]
Try [r573 ](https://github.com/zios/unity-themes/releases/tag/r573) and let me know if your issue persists.

**Comment by PyroclasticMayhem** [comment]
The Classy theme works. Simplicity theme is not rendering properly.
![screenshot from 2017-03-18 14-07-58](https://cloud.githubusercontent.com/assets/2822125/24074718/5cd6f1c0-0be4-11e7-9afd-50efc1a8354d.png)

**Comment by bradsmithee** [comment]
The issue relates to Simplicity.guiSkin -> `dockAreaOverlay` style  -> border field.  The _top_ component.  I've seen it reported one other time, but I cannot replicate it on my end.  Setting the top value from 3 to 1 should resolve it.  What OS and GPU are you using?

**Comment by PyroclasticMayhem** [comment]
Arch Linux, NVIDIA GTX 960. Running Unity 5.6.0xb10.

**Comment by bradsmithee** [comment]
The other user was running a GTX 970.  This could be an Nvidia-related issue.  I'll try to get some additional tests on Intel/AMD chips to confirm.

**Comment by JadenKorn** [comment]
I've tried it with the integrated Intel Graphics HD 4000 series GPU, and it did work properly when `dockAreaOverlay` style is set to 1, as it should be. But it indeed doesn't work as it should when it's the same for GTX 970.

**Comment by bradsmithee** [comment]
Appears fine on both Intel and AMD.  The issue on Nvidia cards seems to be related to the style using a non-power-of-two texture.  Will commit a texture zip hotfix (which should work fine with all vendors).

**Comment by bradsmithee** [comment]
Adjusted dockOverlay texture from 3x3 to 8x8.  
Resolved in [r573 release](https://github.com/zios/unity-themes/releases).
